NDefines.NGame.END_DATE = "1952.1.1.1"
NDefines.NGraphics.COUNTRY_FLAG_TEX_MAX_SIZE = 2048
NDefines.NGraphics.COUNTRY_FLAG_SMALL_TEX_MAX_SIZE = 512
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_WIDTH = 10
NDefines.NGraphics.COUNTRY_FLAG_STRIPE_TEX_MAX_HEIGHT = 8196
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_WIDTH = 41
NDefines.NGraphics.COUNTRY_FLAG_LARGE_STRIPE_MAX_HEIGHT = 24000
-- Focuses
NDefines.NFocus.MAX_SAVED_FOCUS_PROGRESS = 30

NDefines.NDiplomacy.TENSION_DECAY = 0.3
NDefines.NDiplomacy.TENSION_ANNEX_CORE = 0.1
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.1
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 45
NDefines.NDiplomacy.BASE_SEND_ATTACHE_COST = 75

NDefines.NCountry.BASE_MAX_COMMAND_POWER = 200
NDefines.NCountry.POLITICAL_POWER_CAP = 50000
NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.2
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.1
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 40

NDefines.NProduction.BASE_FACTORY_SPEED = 6.5
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 6
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 3.5
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 15
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.CONVERSION_SPEED_BONUS = 3
NDefines.NProduction.BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 60
NDefines.NProduction.BASE_FACTORY_EFFICIENCY_VARIANT_CHANGE_FACTOR = 95

NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 1.75
NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 45

NDefines.NBuildings.MAX_SHARED_SLOTS = 500
NDefines.NBuildings.AIRBASE_CAPACITY_MULT = 250
NDefines.NBuildings.ROCKETSITE_CAPACITY_MULT = 250


NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 2
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 2
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 2


NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 7


NDefines.NMilitary.DEPLOY_TRAINING_MAX_LEVEL = 5
NDefines.NMilitary.UNIT_EXP_LEVELS = {0.02,	0.04, 0.06,	0.08, 0.1, 0.14, 0.18, 0.22, 0.26, 0.3, 0.39, 0.48, 0.57, 0.66, 0.75, 0.78, 0.81, 0.84, 0.87, 0.9}
NDefines.NMilitary.ARMY_EXP_BASE_LEVEL = 5
NDefines.NMilitary.TRAINING_MAX_LEVEL = 10
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 50000
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 50000
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 50000
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.05
NDefines.NMilitary.RECON_SKILL_IMPACT = 6
NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 32
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 96
NDefines.NMilitary.PLANNING_MAX = 0.4
NDefines.NMilitary.STRATEGIC_SPEED_BASE = 15
NDefines.NMilitary.UNIT_DIGIN_CAP = 6
NDefines.NMilitary.UNIT_EXPERIENCE_PER_TRAINING_DAY = 0.0018

NDefines.NMilitary.COMMANDER_LEVEL_UP_STAT_COUNT = 5

NDefines.NMilitary.TACTIC_SWAP_FREQUENCEY = 12
NDefines.NMilitary.BASE_LEADER_TRAIT_GAIN_XP = 0.7
NDefines.NMilitary.UNIT_EXPERIENCE_PER_COMBAT_HOUR = 0.000175
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 12
NDefines.NMilitary.SPEED_REINFORCEMENT_BONUS = 0.1
NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0.1
NDefines.NMilitary.PLAYER_ORDER_PLANNING_DECAY = 0.005
NDefines.NMilitary.PLAN_SUPPLY_FACTOR = 0.2
NDefines.NMilitary.DISBAND_MANPOWER_LOSS = 0.0
NDefines.NMilitary.BASE_CAPTURE_EQUIPMENT_RATIO = 0.01
NDefines.NMilitary.FIELD_MARSHAL_XP_RATIO = 0.7
NDefines.NMilitary.NEW_COMMANDER_RANDOM_BASIC_TRAIT_CHANCES = {0.8, 0.5, 0.2}

NDefines.NMilitary.COMBAT_MINIMUM_TIME = 3
NDefines.NMilitary.BASE_COMBAT_WIDTH = 100
NDefines.NMilitary.ADDITIONAL_COMBAT_WIDTH = 80

-- Air Combat
NDefines.NAir.AIR_WING_XP_LEVELS = {20, 40, 60, 80, 100, 140, 180, 220, 260, 300, 390, 480, 570, 660, 750, 780, 810, 840, 870, 900}
NDefines.NAir.AIR_WING_XP_TRAINING_MAX = 300.0
NDefines.NAir.AIR_WING_XP_TRAINING_MISSION_GAIN_DAILY = 4.5
NDefines.NAir.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0.01
NDefines.NAir.AIR_WING_XP_LOSS_WHEN_KILLED = 200
NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 200 -- Max stats
NDefines.NAir.AIR_WING_MAX_STATS_DEFENCE = 200
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 200
NDefines.NAir.AIR_WING_MAX_STATS_SPEED = 1500 -- Used to balance the damage done while bombing.
NDefines.NAir.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0.0075
NDefines.NAir.BOMBING_TARGETING_RANDOM_FACTOR = 0.05
NDefines.NAir.MISSION_COMMAND_POWER_COSTS = { -- command power cost per plane to create a mission
		0.0, -- AIR_SUPERIORITY
		0.0, -- CAS
		0.0, -- INTERCEPTION
		0.0, -- STRATEGIC_BOMBER
		0.0, -- NAVAL_BOMBER
		0.0, -- DROP_NUKE
		0.0, -- PARADROP
		0.0, -- NAVAL_KAMIKAZE
		0.0, -- PORT_STRIKE
		0.01, -- AIR_SUPPLY
		0.0, -- TRAINING
		0.0, -- NAVAL_MINES_PLANTING
		0.0, -- NAVAL_MINES_SWEEPING
    }

