NDefines.NGame.END_DATE = "1952.1.1.1"

NDefines.NDiplomacy.TENSION_DECAY = 0.3
NDefines.NDiplomacy.TENSION_ANNEX_CORE = 0.1
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.1
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 45
NDefines.NDiplomacy.BASE_SEND_ATTACHE_COST = 75

NDefines.NCountry.BASE_MAX_COMMAND_POWER = 200
NDefines.NCountry.POLITICAL_POWER_CAP = 50000
NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.2

NDefines.NProduction.BASE_FACTORY_SPEED = 6
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 5.5
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 3.5
NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 15
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.CONVERSION_SPEED_BONUS = 3
NDefines.NProduction.BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 60
NDefines.NProduction.BASE_FACTORY_EFFICIENCY_VARIANT_CHANGE_FACTOR = 95

NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 1.75
NDefines.NTechnology.BASE_RESEARCH_POINTS_SAVED = 45

NDefines.NBuildings.MAX_SHARED_SLOTS = 500
NDefines.NBuildings.ROCKETSITE_CAPACITY_MULT = 250

NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 50000
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 50000
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 50000

NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 2
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 2
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 2

NDefines.NMilitary.CORPS_COMMANDER_DIVISIONS_CAP = 32
NDefines.NMilitary.FIELD_MARSHAL_DIVISIONS_CAP = 96
NDefines.NMilitary.FIELD_MARSHAL_ARMIES_CAP = 7
NDefines.NMilitary.COMMANDER_LEVEL_UP_STAT_COUNT = 5
NDefines.NMilitary.NEW_COMMANDER_RANDOM_BASIC_TRAIT_CHANCES = {0.8, 0.5, 0.2}

NDefines.NMilitary.COMBAT_MINIMUM_TIME = 3
NDefines.NMilitary.BASE_COMBAT_WIDTH = 100
NDefines.NMilitary.ADDITIONAL_COMBAT_WIDTH = 80

NDefines.NAir.AIR_WING_MAX_STATS_ATTACK = 150
NDefines.NAir.AIR_WING_MAX_STATS_AGILITY = 200
NDefines.NAir.AIR_WING_MAX_STATS_BOMBING = 150 
NDefines.NAir.ACE_WING_SIZE_MAX_BONUS = 9
