NDefines.NGame.END_DATE = "1950.1.1.1"


NDefines.NCountry.BASE_MAX_COMMAND_POWER = 200
NDefines.NCountry.POLITICAL_POWER_CAP = 50000
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 50000
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 50000
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 50000
NDefines.NBuildings.MAX_SHARED_SLOTS = 500
NDefines.NMilitary.MAX_DIVISION_SUPPORT_WIDTH = 2
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 5
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 2
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 3
NDefines.NAir.ACE_WING_SIZE_MAX_BONUS = 8